[package]
name = "micro-tower"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
	"codegen",
	"core",
	"runtime"
]

[dependencies.tokio]
version = "~1.20.1"
features = ["full"]

[dependencies.tower]
version = "~0.4.13"
features = ["full"]

[dependencies.micro-tower-core]
path = "core/"

[dependencies.micro-tower-runtime]
path = "runtime/"

[dependencies.micro-tower-codegen]
path = "codegen/"
