[package]
name = "micro-tower"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
	"codegen",
]

[dependencies]
derive_builder = "~0.11.2"

[dependencies.tokio]
version = "~1.21.0"
features = ["full"]

[dependencies.tower]
version = "~0.4.13"
features = ["full"]

[dependencies.micro-tower-codegen]
path = "codegen/"
